name: Prisma Cloud Checkov Scan

on:
  push:
    branches:
      - main

jobs:
  prisma-checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.sg.prismacloud.io  # ← 여긴 그대로 사용해도 됨
        with:
          api-key: ${{ secrets.BC_API_KEY }}
